// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PumiikaVChiniika.Models;

public partial class Recipe
{
    public int RecipeId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int PreparationTime { get; set; }

    public string Difficulty { get; set; }

    public int CategoryId { get; set; }

    public string Instructions { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<RecipeIngredient> RecipeIngredients { get; set; } = new List<RecipeIngredient>();
}